# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Buckley Williams
email: hi@buckleywilliams.com
description: > # this means to ignore newlines until "baseurl:"
  A small consultancy that helps teams explore technology.

  We mix research, workshops and working code to help companies think about the future.

  We’ve prototyped new products, investigated technology policy, taught people new digital skills and done a bunch of other stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://buckleywilliams.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BuckleyWilliams
collections:
  case_studies:
    output: true
    permalink: /case-studies/:path/
  projects:
    output: true
    permalink: /work/:path/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: ./assets
